sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - "8.11.1"
  - "9.10.1"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn add codecov
script:
  - yarn test
after_success:
  - node ./node_modules/.bin/codecov -f coverage/*.json
